spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/voa
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  servlet:
    multipart:
      enabled: true # 파일 업로드 가능 여부
      location: C:\\upload\

# JWT를 위해서 영문숫자 조합의 32글자 이상의 키가 필요
jwt:
  secret: # 다음 명령어로 생성한 암호키. -> $ openssl rand -hex 32