spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/voa
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  sql:
    init:
      mode: never # DB 최초 구축 시에만 always로 변경

  jpa:
    hibernate:
      ddl-auto: none # create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      enabled: true # 파일 업로드 가능 여부
      location: C:\\upload\

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key가 필요
jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK